### ISSUE TITLE
Support to lists

### ISSUE THREAD

**Issue by yolandab** [bsc-dd/hecuba#117]
The manual states that hecuba supports the list type but the only operation supported is the assignment of a list to an attribute and the retrieval on a python list. 
``` python
class myclass(StorageObj):
   '''
   @Classfield mylist <int>
   '''

o=myclass()
l1=[1,2,3]
o.mylist=l1 #this works
l2=o.mylist #this works
o.mylist.append(4) #this fails
```
So we should add the operations on lists and,  in my opinion, in the mean time as our current support is very limited we should avoid talking about it

**Comment by cugni** [comment]
related to #17

**Comment by polsm91** [comment]
Manual fixed
