### ISSUE TITLE
Compatibility with numpy library

### ISSUE THREAD

**Issue by yolandab** [bsc-dd/hecuba#132]
We need to check the compatibility with the functions implemented in numpy library. 
Upgrading the numpy library I have found the following situation.

Given the class definition:
```python 
class dataClass(StorageObj):
   '''
      @ClassField numbers numpy.ndarray 
      @ClassField average numpy.ndarray
      @ClassField stdev double
   '''
   pass
````
Using the version 1.13 of numpy library we have the following behaviour:
```python
In [1]: import numpy as np
In [2]: n=np.random.rand(10)
In [3]: a=np.average(n)
In [4]: type(a)
Out[4]: numpy.float64
In [5]: st=np.std(n)
In [6]: type(st)
Out[6]: numpy.float64
In [7]: from dataClass import dataClass
In [8]: myobj=dataClass("mynumbers")
In [9]: myobj.numbers=np.random.rand(10)
In [10]: a=np.average(myobj.numbers)
In [11]: type(a)
Out[11]: hecuba.hnumpy.StorageNumpy
In [12]: st=np.std(myobj.numbers)
In [13]: type(st)
Out[13]: hecuba.hnumpy.StorageNumpy
```
However, using older versions of numpy library (1.9 or earlier):
```python
In [1]: import numpy as np
In [2]: n=np.random.rand(10)
In [3]: a=np.average(n)
In [4]: type(a)
Out[4]: numpy.float64
In [5]: st=np.std(n)
In [6]: type(st)
Out[6]: numpy.float64
In [7]: from dataClass import dataClass
In [8]: myobj=dataClass("mynumbers")
In [9]: myobj.numbers=np.random.rand(10)
In [10]: a=np.average(myobj.numbers)
In [11]: type(a)
Out[11]: numpy.float64
In [12]: st=np.std(myobj.numbers)
In [13]: type(st)
Out[13]: numpy.float64
```

**Comment by cugni** [comment]
I think we should just put in the requirements.txt that we support only the last numpy version (1.13 and so on )

**Comment by yolandab** [comment]
The last version that works for the average and the std function  is 1.9.  In any case, we should check the specification of the rest of the  numpy library functions. In the release notes of the 1.13 library I have read that the changes on the average function are to make it equivalent to other cases in the library.

**Comment by polsm91** [comment]
@yolandab 
I have already checked. The future behaviour is the new one for all the methods. Discussed on (https://github.com/numpy/numpy/issues/7403)

They use this method (https://github.com/numpy/numpy/blob/master/numpy/core/numeric.py#L494) which preserves the data type, instead of (https://github.com/numpy/numpy/blob/master/numpy/core/numeric.py#L423) on the new methods, for example in here (https://github.com/numpy/numpy/blob/4cbced22a8306d7214a4e18d12e651c034143922/numpy/core/_methods.py#L53)
