### ISSUE TITLE
QBeastIterator doesn't inherit from Object

### ISSUE THREAD

**Issue by polsm91** [bsc-dd/hecuba#133]
When integrating Hecuba with PyCOMPSs we discovered that the type of QBeastIterator or the elements returned by QBeastIterator.split() are of type "instance". This happens because the class inherits only from IStorage and not from Object.

If there is no reason for that, I think we should inherit also from Object because makes debugging easier and enables type checking.

**Comment by cugni** [comment]
I'm pretty sure you are confused. Split is a method, it returns whatever it
wants, it does not depend on the class inheritance.

Il mer 25 ott 2017, 20:19 polsm91 <notifications@github.com> ha scritto:

**Comment by polsm91** [comment]
I opened the issue so we know and remember why this happens and decide whether to change it.

I know, it returns an object of the same type who called it, in this case, returns a QBeastIterator. I wrote that because we identified the that python reported QBeastIterator.split() was returning an object of type "instance". 
The origin of this behaviour is QBeastIterator not inheriting from Object.

**Comment by cugni** [comment]
Are you sure you are not confusing the object inheritance? What you mean
for instance?
Il giorno mer 25 ott 2017 alle 13:19 polsm91 <notifications@github.com> ha
scritto:

**Comment by polsm91** [comment]
https://github.com/bsc-dd/hecuba/blob/9b251e4c86942db1d7c06d0315f8187130f79e4e/hecuba/qbeast.py#L29
``` python
class QbeastIterator(IStorage):
    pass

MyObj = QbeastIterator()
print type(MyObj) #This prints exactly: <type 'instance'>
```

instead, if you do:
``` python
class QbeastIterator(IStorage, object):
    pass

MyObj = QbeastIterator()
print type(MyObj) #This prints exactly: <type 'QBeastIterator'>
```

This happens in Python 2 (version > 2.2). It has other consequences explained here:
https://stackoverflow.com/questions/54867/what-is-the-difference-between-old-style-and-new-style-classes-in-python
