### ISSUE TITLE
getID function is returning string "None" instead of NoneType

### ISSUE THREAD

**Issue by eloygil** [bsc-dd/hecuba#144]
Casting everything to string is fine until this happens. We should remove, at least, those that are not needed and check the types of the returned variables.

**Comment by cugni** [comment]
why getID should return NoneType?

**Comment by eloygil** [comment]
This situation only appears when using PyCOMPSs, it is returned a StorageObj that is a future object and has no identifier. They are expecting it, as Dataclay is already doing it this way. We can discuss about this later.
