### ISSUE TITLE
The field 'name' in istorage for storage objects containing numpys is wrong

### ISSUE THREAD

**Issue by yolandab** [bsc-dd/hecuba#146]
This field should be composed of keyspace and table name: ks_name.table_name. However for storage objects containing numpys it only contains the table name.
It is fixed with the following changes:
 

- line 111 in file hecuba/hnumpy.py :
```python
self._build_args = self.args(self._storage_id, self._class_name, name)
```
should be:
```python
self._build_args = self.args(self._storage_id, self._class_name, self._ksp+'.'+self._table)
```

- line 347 in hecuba/storageobj.py
```python
self._build_args = self._build_args._replace(name=name)
```
should be:
```python
self._build_args = self._build_args._replace(name=self._ksp+'.'+self._table)
```

**Comment by polsm91** [comment]
Also the following lines have a wrong name argument:

hecuba/hdict.py:166:        self._build_args = self.args(name, self._primary_keys, self._columns, self._tokens,

hecuba/hnumpy.py:111:        self._build_args = self.args(self._storage_id, self._class_name, name)


hecuba/qbeast.py:124:        self._build_args = self._building_args(

**Comment by polsm91** [comment]
Fixed
