### ISSUE TITLE
Support for gcc 4.8.5

### ISSUE THREAD

**Issue by eloygil** [bsc-dd/hecuba#160]
If fails to build tbb with this version of gcc.
It works enabling c++11 adding a flag like:
```cmake
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC") #old
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC -std=c++11")
```
In the CMakeLists. We should check which flags we need for each GCC version.

**Comment by cugni** [comment]
We should also test Hecuba with different gcc version. We can do it with travis https://github.com/taocpp/PEGTL/blob/master/.travis.yml

**Comment by polsm91** [comment]
Tested with `gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)`

Needs to:
```bash
export CFLAGS="-std=c++11 $CFLAGS"
```
For old compilers.

The reason is Python tries to compile Hecuba with the flags it was compiled and it has no mechanism to check for C++11/14/17 support.
