### ISSUE TITLE
Fix hands-on (duplicated, and Python 3)

### ISSUE THREAD

**Issue by polsm91** [bsc-dd/hecuba#261]
We have two Hands-on versions:

https://github.com/bsc-dd/hecuba/wiki/1:-User-Manual#2-hecuba-hands-on

and

https://github.com/bsc-dd/hecuba/wiki/2:-Hecuba-Hands-On

We need to check which is the most up-to-date and upgrade the examples to Python 3.

**Comment by adrianespejo** [comment]
The two hands-on versions were almost the same. The one in 1: User Manual was in Python 3 and the one in 2: Hecuba Hands On was in Python 2. I deleted the hands-on in 1: User Manual and updated both examples in 2: Hecuba Hands On.

**Comment by polsm91** [comment]
Perfect, thank you!
