### ISSUE TITLE
StorageItf.java - getLocations change for StorageObjs

### ISSUE THREAD

**Issue by guillemalomar** [bsc-dd/hecuba#56]
Now when a call to the getLocations method in StorageItf.jar with an ID of a StorageObj should return a list with all the PyCOMPSs worker locations (opposed to what it was returned before; an empty list).
Where will we take those locations? Maybe reading from /etc/hosts (so that the names are the same that the system returns).
P.D.: don't ask why they have changed it.

**Comment by polsm91** [comment]
@yolandab @cugni This is already solved right?
